version: '3.3'

services:
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_DB=precipitacion_web
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123

    ports:
      - 5432:5432

    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=jairalan1406@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root

    ports:
      - 5050:80

    volumes:
      - my_data:/var/lib/pgadmin

volumes:
  my_data: